"""Deterministic fake providers used for tests and offline runs.

These never call the network and never require an API key. They produce
deterministic output that downstream code can validate.

Each provider tracks `call_count` so tests can prove that cache hits skip
the underlying provider call.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from urdu_pipeline.providers.base import (
    TextGenerationResult,
    TranscriptionResult,
)
from urdu_pipeline.providers.requests import (
    AudioTranscriptionRequest,
    TextGenerationRequest,
    coerce_audio_transcription_request,
    coerce_text_generation_request,
)


def _stable_hash(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:16]


_FAKE_TRANSCRIPT_TEMPLATE = (
    "بسم اللہ الرحمن الرحیم۔ "
    "یہ ایک نمونہ اردو متن ہے جو ٹیسٹ کے لیے تیار کیا گیا ہے۔ "
    "اس میں chunk_index کی شناخت کے لیے ایک نمبر بھی شامل ہے: "
    "[chunk={chunk_index}] [غیر واضح] "
    "اللہ ہم سب کو ہدایت دے۔"
)

_FAKE_TRANSCRIPT_TEMPLATE_EN_US = (
    "In the name of Allah, the Most Gracious, the Most Merciful. "
    "This is a sample American English transcript chunk for testing. "
    "[chunk={chunk_index}] [unclear] "
    "May Allah guide us all."
)


class FakeAudioTranscriptionProvider:
    name = "fake"

    def __init__(self) -> None:
        self.call_count = 0

    def transcribe_chunk(
        self,
        chunk_path: AudioTranscriptionRequest | Path | str,
        prompt: str | None = None,
        model_id: str | None = None,
        language_hint: str | None = None,
    ) -> TranscriptionResult:
        request = coerce_audio_transcription_request(
            chunk_path,
            prompt=prompt,
            model_id=model_id,
            language_hint=language_hint,
        )
        self.call_count += 1
        # `chunk_index` is encoded in the chunk filename (chunk_NNNN).
        try:
            stem = Path(request.chunk_path).stem  # e.g. "chunk_0003"
            idx = int(stem.split("_")[-1])
        except Exception:
            idx = self.call_count
        if request.language_hint == "en":
            text = _FAKE_TRANSCRIPT_TEMPLATE_EN_US.format(chunk_index=idx)
        else:
            text = _FAKE_TRANSCRIPT_TEMPLATE.format(chunk_index=idx)
        return TranscriptionResult(
            text=text,
            model_id=request.model_id,
            duration_seconds=300.0,
            actual_usage={"call_count": self.call_count, "fake": True},
            provider_metadata={
                "fake": True,
                "input_hint": _stable_hash(request.prompt_text + str(request.chunk_path)),
                "chunk_index": idx,
            },
        )


_FAKE_RECONCILE_NOTE = (
    "[reconciled] "
    "بسم اللہ الرحمن الرحیم۔ "
    "یہ ایک نمونہ اردو متن ہے جو ٹیسٹ کے لیے تیار کیا گیا ہے۔ "
    "[غیر واضح] "
    "اللہ ہم سب کو ہدایت دے۔"
)

_FAKE_TRANSLATION_TEMPLATE = (
    "[fake-translation]\n\n"
    "In the name of Allah, the Most Gracious, the Most Merciful. "
    "This is a sample Urdu text prepared for testing. "
    "[unclear] May Allah guide us all.\n\n"
    "Religious terms preserved: humility (*tawāḍuʿ*), sincerity (*ikhlāṣ*).\n"
)

_FAKE_ARTICLE_JSON = (
    '{\n'
    '  "title": "A Sample Reflection on Sincerity and Humility",\n'
    '  "subtitle": "Notes from a translated lecture (test fixture)",\n'
    '  "body_markdown": "## Introduction\\n\\n'
    'In the name of Allah, the Most Gracious, the Most Merciful. '
    'This sample article is generated by the fake provider so that the '
    'pipeline can be exercised end-to-end without network access.\\n\\n'
    '## Sincerity and Humility\\n\\n'
    'The lecture reminds us of two foundational qualities: humility '
    '(*tawāḍuʿ*) and sincerity (*ikhlāṣ*). Sections marked [unclear] '
    'in the source are preserved here so the reader knows where the '
    'recording was hard to follow.\\n\\n'
    '## Closing\\n\\n'
    'May Allah guide us all."\n'
    '}'
)


class FakeTextGenerationProvider:
    name = "fake"

    def __init__(self) -> None:
        self.call_count = 0
        self.last_prompt: str | None = None
        self.last_input: str | None = None

    def generate(
        self,
        request: TextGenerationRequest | str | None = None,
        input_text: str | None = None,
        model_id: str | None = None,
        max_output_tokens: int | None = None,
        *,
        prompt: str | None = None,
    ) -> TextGenerationResult:
        request_obj = coerce_text_generation_request(
            request,
            input_text=input_text,
            model_id=model_id,
            max_output_tokens=max_output_tokens,
            prompt=prompt,
        )
        self.call_count += 1
        self.last_prompt = request_obj.instruction_text
        self.last_input = request_obj.source_text

        prompt_lower = request_obj.instruction_text.lower()
        if "reconciliation" in prompt_lower or "merging overlapping" in prompt_lower:
            text = _FAKE_RECONCILE_NOTE
        elif "translating" in prompt_lower or "american english" in prompt_lower and "article" not in prompt_lower:
            text = _FAKE_TRANSLATION_TEMPLATE
        elif "standalone" in prompt_lower or "article" in prompt_lower:
            text = _FAKE_ARTICLE_JSON
        else:
            text = "[fake-generation]\n" + request_obj.source_text[:500]

        return TextGenerationResult(
            text=text,
            model_id=request_obj.model_id,
            actual_usage={"call_count": self.call_count, "fake": True},
            provider_metadata={
                "fake": True,
                "input_hint": _stable_hash(
                    request_obj.instruction_text + request_obj.source_text
                ),
            },
        )
