"""OpenAPI schema validation tests — Step 4.3.5.

Tests validate key properties of the generated schema without requiring a
brittle full-content snapshot.  The assertions focus on:

  1. The schema is reachable and structurally valid.
  2. All expected public routes are documented.
  3. No internal identifiers (user_id, job_id, raw object keys, provider
     details) appear in any request or response schema.
  4. The one-time raw token value is not exposed in list or summary schemas.
  5. No prohibited provider/model/prompt fields appear anywhere.

A machine-readable snapshot is generated by the implementation step and
saved to ``docs/openapi.json`` for offline review and diffing.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from urdu_pipeline.api.app import create_app
from urdu_pipeline.api.dependencies import AppState
from urdu_pipeline.infrastructure.in_memory import (
    InMemoryCacheStore,
    InMemoryMetadataStore,
    InMemoryObjectStore,
    InMemorySecretProvider,
)


# ── Fixture ───────────────────────────────────────────────────────────────────


@pytest.fixture(scope="module")
def schema() -> dict:
    """Fetch the OpenAPI schema from the app once for all tests in this module."""
    state = AppState(
        metadata_store=InMemoryMetadataStore(),
        object_store=InMemoryObjectStore(),
        cache_store=InMemoryCacheStore(),
        secret_provider=InMemorySecretProvider(),
    )
    client = TestClient(create_app(state=state))
    resp = client.get("/openapi.json")
    assert resp.status_code == 200, "OpenAPI schema endpoint must return 200"
    return resp.json()


# ── Helper ────────────────────────────────────────────────────────────────────


def _all_property_names(obj: object) -> set[str]:
    """Recursively extract every property name from a JSON Schema object."""
    names: set[str] = set()
    if isinstance(obj, dict):
        if "properties" in obj and isinstance(obj["properties"], dict):
            names.update(obj["properties"].keys())
        for v in obj.values():
            names.update(_all_property_names(v))
    elif isinstance(obj, list):
        for item in obj:
            names.update(_all_property_names(item))
    return names


# ── Structural tests ──────────────────────────────────────────────────────────


def test_schema_has_required_openapi_keys(schema):
    assert "openapi" in schema
    assert "info" in schema
    assert "paths" in schema


def test_schema_openapi_version(schema):
    assert schema["openapi"].startswith("3.")


def test_schema_has_title(schema):
    assert schema["info"]["title"] != ""


def test_schema_has_paths(schema):
    assert len(schema["paths"]) > 0


# ── Route presence tests ──────────────────────────────────────────────────────


_EXPECTED_PATHS = [
    # health
    ("/health", "get"),
    # auth
    ("/auth/login", "post"),
    ("/auth/logout", "post"),
    # tokens
    ("/tokens", "post"),
    ("/tokens", "get"),
    ("/tokens/{token_id}", "delete"),
    # single-part upload
    ("/uploads/init", "post"),
    ("/uploads/{upload_id}", "get"),
    ("/uploads/{upload_id}/complete", "post"),
    # multipart upload
    ("/uploads/multipart/init", "post"),
    ("/uploads/multipart/{upload_id}/parts/{part_number}", "get"),
    ("/uploads/multipart/{upload_id}/complete", "post"),
    ("/uploads/multipart/{upload_id}", "delete"),
    # direct upload
    ("/uploads/direct", "post"),
    # runs
    ("/runs", "post"),
    ("/runs", "get"),
    ("/runs/{run_id}", "get"),
    ("/runs/{run_id}/events", "get"),
    ("/runs/{run_id}/cancel", "post"),
    # artifacts (nested under runs and as top-level)
    ("/runs/{run_id}/artifacts", "get"),
    ("/artifacts/{artifact_id}", "get"),
    ("/artifacts/{artifact_id}/download", "get"),
]


@pytest.mark.parametrize("path,method", _EXPECTED_PATHS)
def test_expected_route_is_documented(schema, path, method):
    """Every public route must appear in the OpenAPI schema."""
    assert path in schema["paths"], f"Missing path: {path}"
    assert method in schema["paths"][path], f"Missing method {method.upper()} for {path}"


# ── No internal identifier leakage ────────────────────────────────────────────


def test_user_id_not_in_any_schema_property(schema):
    """user_id must never appear as a schema property — it is internal."""
    all_props = _all_property_names(schema.get("components", {}).get("schemas", {}))
    assert "user_id" not in all_props, (
        "user_id appeared as a property name in a schema component. "
        "It must never be returned to or accepted from callers."
    )


def test_job_id_not_in_any_response_schema(schema):
    """job_id must not appear in any schema — it is an internal queue concept."""
    all_props = _all_property_names(schema.get("components", {}).get("schemas", {}))
    assert "job_id" not in all_props


def test_object_key_not_in_any_schema(schema):
    """Raw object-store keys must never be part of the public API surface."""
    all_props = _all_property_names(schema.get("components", {}).get("schemas", {}))
    assert "object_key" not in all_props
    assert "key" not in all_props


def test_no_provider_fields_in_any_schema(schema):
    """Provider configuration must not be controllable by callers."""
    all_props = _all_property_names(schema.get("components", {}).get("schemas", {}))
    for forbidden in ("provider", "model_id", "prompt", "api_key"):
        assert forbidden not in all_props, (
            f"Forbidden field {forbidden!r} appeared in schema. "
            "Provider/model/prompt fields must not be caller-controlled."
        )


# ── Token raw-value policy ────────────────────────────────────────────────────


def test_token_list_schema_does_not_include_raw_token(schema):
    """TokenListResponse/TokenSummary must not expose the raw token value."""
    token_list = schema.get("components", {}).get("schemas", {}).get("TokenListResponse", {})
    props = _all_property_names(token_list)
    assert "token" not in props, (
        "TokenListResponse exposes the raw 'token' field. "
        "The raw value must only appear in the creation response."
    )


def test_token_summary_does_not_include_raw_token(schema):
    summary = schema.get("components", {}).get("schemas", {}).get("TokenSummary", {})
    props = _all_property_names(summary)
    assert "token" not in props


# ── Request schema extra-field policy ─────────────────────────────────────────


def test_upload_init_request_does_not_accept_user_id(schema):
    """InitUploadRequest must not accept user_id from callers."""
    req_schema = schema.get("components", {}).get("schemas", {}).get("InitUploadRequest", {})
    assert req_schema, "InitUploadRequest schema not found in components"
    props = set((req_schema.get("properties") or {}).keys())
    assert "user_id" not in props
    assert "object_key" not in props


def test_run_request_does_not_accept_provider_fields(schema):
    """CreateRunRequest must not accept provider or model configuration."""
    req_schema = schema.get("components", {}).get("schemas", {}).get("CreateRunRequest", {})
    assert req_schema, "CreateRunRequest schema not found"
    props = set((req_schema.get("properties") or {}).keys())
    assert "provider" not in props
    assert "model_id" not in props
    assert "prompt" not in props


# ── Snapshot generation (not a test, called by a test) ───────────────────────


def test_openapi_snapshot_is_saved(schema):
    """Write the current schema to docs/openapi.json for human review and diffing.

    This test always passes; the generated file is the deliverable.
    """
    workspace = Path(__file__).parent.parent.parent
    docs_dir = workspace / "docs"
    docs_dir.mkdir(exist_ok=True)
    output = docs_dir / "openapi.json"
    output.write_text(json.dumps(schema, indent=2, ensure_ascii=False))
    assert output.exists()
